name: Streamlit Keep Alive

on:
  schedule:
    # 毎日 日本時間の深夜2時（UTC 17:00）に実行
    - cron: '0 17 * * *'
  workflow_dispatch: # 手動でもボタンから実行できます

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update keep_alive.txt
        run: |
          date > keep_alive.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add keep_alive.txt
          git commit -m "Keep alive: $(date)"
          git push
